// Printable payslip for one employee's month, opened in its own window so it
// prints cleanly (and "Save as PDF" works) regardless of the app's styles.
import { computeRow, formatRupees, monthLabel } from "../../services/payrollService";

const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (ch) => ({
  "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
}[ch]));

export const payslipHtml = (rawRow, month, { restaurantName = "OrderIn Restaurant" } = {}) => {
  const row = computeRow(rawRow);
  const line = (label, amount, note = "") => `<tr><td>${escapeHtml(label)}${note ? `<div class="note">${escapeHtml(note)}</div>` : ""}</td><td class="amt">${formatRupees(amount)}</td></tr>`;
  const additions = [
    line("Salary", row.salary),
    Number(row.increment) > 0 ? line("Increment", row.increment, "Added to your salary from next month") : "",
    Number(row.bonus) > 0 ? line("Bonus", row.bonus) : "",
  ].join("");
  const deductions = [
    Number(row.tax) > 0 ? line("Employment tax", row.tax) : "",
    Number(row.pf) > 0 ? line("Provident fund (PF)", row.pf) : "",
    Number(row.insurance) > 0 ? line("Insurance", row.insurance) : "",
    ...(row.extraDeductions || []).map((d) => line(d.reason || "Other", d.amount)),
  ].join("") || `<tr><td colspan="2" class="note">No deductions</td></tr>`;
  return `<!doctype html><html><head><meta charset="utf-8"><title>Payslip ${escapeHtml(row.staffName)} ${escapeHtml(month)}</title>
<style>
  body { font-family: system-ui, -apple-system, "Segoe UI", sans-serif; color: #1c2b22; margin: 32px; }
  .slip { max-width: 620px; margin: 0 auto; border: 1px solid #c9d3cc; border-radius: 10px; padding: 24px 28px; }
  h1 { font-size: 20px; margin: 0; } h2 { font-size: 14px; margin: 18px 0 6px; color: #3d5a47; text-transform: uppercase; letter-spacing: .04em; }
  .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 4px 16px; font-size: 13px; margin-top: 12px; }
  table { width: 100%; border-collapse: collapse; font-size: 14px; }
  td { padding: 6px 0; border-bottom: 1px solid #e6ebe7; vertical-align: top; }
  .amt { text-align: right; white-space: nowrap; font-variant-numeric: tabular-nums; }
  .total td { font-weight: 700; border-bottom: none; }
  .net { margin-top: 16px; padding: 12px 14px; background: #eef4ef; border-radius: 8px; display: flex; justify-content: space-between; font-size: 16px; font-weight: 700; }
  .note { font-size: 11px; color: #6b7d71; }
  .foot { margin-top: 18px; font-size: 11px; color: #6b7d71; }
  @media print { body { margin: 0; } .slip { border: none; } }
</style></head><body><div class="slip">
  <h1>${escapeHtml(restaurantName)} — Payslip</h1>
  <div class="note">${escapeHtml(monthLabel(month))}</div>
  <div class="meta">
    <div><strong>Employee:</strong> ${escapeHtml(row.staffName)}</div>
    <div><strong>Employee ID:</strong> ${escapeHtml(row.employeeId || "—")}</div>
    <div><strong>Role:</strong> ${escapeHtml(row.jobRole || row.accessRole || "—")}</div>
    <div><strong>Payment:</strong> ${escapeHtml(row.paymentStatus === "paid" ? `Paid · ${row.paymentReference || ""}` : "Pending")}</div>
  </div>
  <h2>Additions</h2><table>${additions}<tr class="total"><td>Total additions</td><td class="amt">${formatRupees(row.additions)}</td></tr></table>
  <h2>Deductions</h2><table>${deductions}<tr class="total"><td>Total deductions</td><td class="amt">${formatRupees(row.deductions)}</td></tr></table>
  <div class="net"><span>Net pay</span><span>${formatRupees(row.netPay)}</span></div>
  <div class="foot">Tips are paid directly by customers and are not part of this payslip. Generated by OrderIn.</div>
</div><script>window.onload = () => window.print();</script></body></html>`;
};

export const printPayslip = (row, month, options) => {
  const win = window.open("", "_blank", "width=720,height=900");
  if (!win) {
    window.alert("Allow pop-ups for this site to download the payslip.");
    return;
  }
  win.document.open();
  win.document.write(payslipHtml(row, month, options));
  win.document.close();
};
