// src/services/illusionPricingService.js
import { db } from "../firebase";
import { collection, getDocs, addDoc, Timestamp } from "firebase/firestore";

const RESTAURANT_ID = "orderin_restaurant_4";

const menuRef = () => collection(db, "Restaurant", RESTAURANT_ID, "menu");
const promotionsRef = () => collection(db, "Restaurant", RESTAURANT_ID, "promotions");

/** Fetch all menu items (for picking which dish to promote). */
export const fetchMenuItems = async () => {
  const snap = await getDocs(menuRef());
  return snap.docs.map((d) => ({ id: d.id, ...d.data() }));
};

/**
 * Create a flash "Illusion Pricing" promo tied to a rotting ingredient, so the
 * customer app can surface a discount banner on the linked dish before it spoils.
 */
export const createIllusionPricingPromo = async ({
  menuItem,
  discountPercent,
  durationHours,
  sourceInventoryItemName,
}) => {
  const now = Timestamp.now();
  const expiryAt = Timestamp.fromMillis(now.toMillis() + durationHours * 60 * 60 * 1000);

  const originalPrice = Number(String(menuItem.price).replace(/[^0-9.-]+/g, "")) || 0;
  const discountedPrice = Math.max(0, Math.round(originalPrice * (1 - discountPercent / 100)));

  const promoDoc = {
    caption: `${menuItem.name} — Limited Time Offer`,
    description: `Get ${discountPercent}% off ${menuItem.name} tonight only. Grab it before it's gone!`,
    duration: `${durationHours}h`,
    createdAt: now,
    expiryAt,
    autoGenerated: true,
    linkedMenuItemId: menuItem.id,
    linkedMenuItemName: menuItem.name,
    discountPercent,
    originalPrice,
    discountedPrice,
    sourceInventoryItemName: sourceInventoryItemName || null,
    reason: "rot_index_critical",
  };

  const docRef = await addDoc(promotionsRef(), promoDoc);
  return { id: docRef.id, ...promoDoc };
};
